name: Packages build

on:
  workflow_call:
  workflow_dispatch:
  push: {branches: ["feature/Documentserver-plugins-deb-rpm"]}
    
jobs:
  build_deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    steps:
      - name: Get files from repository. Path /home/runner/work/onlyoffice.github.io/onlyoffice.github.io
        uses: actions/checkout@v2
        
      - name: Install required tools
        run: |
          sudo apt-get install dh-make 
#         sudo apt-get install build-essentials descripts
        shell: bash
      
      - name: Build package with dpkg-buildpackage
        id: deb
        run: |
          cd sdkjs-plugins/packages/deb/onlyoffice-documentserver-plugin-chess
          dpkg-buildpackage -b -uc -us -d 
          ls -la ../
# b - for binary, uc - unsigned changes, us - unsigned source, d - no check build dependencies
        shell: bash
        
        

  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "sdkjs-plugins/packages/rpm/onlyoffice-documentserver-plugin-chess.spec"
     
      - name: Check package
        run: |
          ls -la /github/home/rpmbuild/RPMS/x86_64




