name: Packages build

on:
  workflow_call:
  workflow_dispatch:
  push: {branches: ["feature/Documentserver-plugins-deb-rpm"]}
    
jobs:
  build:
    name: Build .deb package
    runs-on: ubuntu-latest
    steps:
      - name: Get files from repository. Path /home/runner/work/onlyoffice.github.io/onlyoffice.github.io
        uses: actions/checkout@v2
        
      - name: Install required tools
        run: |
          sudo apt-get install dh-make 
#         sudo apt-get install build-essentials
#         sudo apt-get install descripts
        shell: bash
      
      - name: Build package with dpkg-buildpackage
        run: |
          cd sdkjs-plugins/packages/deb/onlyoffice-documentserver-plugin-chess
          dpkg-buildpackage -b -uc -us -d
        shell: bash
          
#      - name: Build package
 #       run: |
  #        dpkg-builpackage -b -uc -us
   #       ls -la ../
    #      pwd
     #     pwd ..
      #  shell: bash

