name: .deb-package build

on:
  workflow_call:
  workflow_dispatch:
  push: {branches: ["feature/Documentserver-plugins-deb-rpm"]}
    
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Get files from repository path /home/runner/work/onlyoffice.github.io/onlyoffice.github.io
        uses: actions/checkout@v2

      - name: Get control files
        run: |
          cd sdkjs-plugins/packages/
          dpkg-buildpackage -b -uc -us

        shell: bash
          
#      - name: Build package
 #       run: |
  #        dpkg-builpackage -b -uc -us
   #       ls -la ../
    #      pwd
     #     pwd ..
      #  shell: bash

