name: Release RPM DEB
on:
  workflow_call:
  workflow_dispatch:
  push: 
    branches: ["feature/Documentserver-plugins-deb-rpm"]
    tags: 
      - '*'

env:
  REPOS_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:


  build_deb:
    name: Build & Release .deb package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Get files from repository. Path /home/runner/work/onlyoffice.github.io/onlyoffice.github.io
        uses: actions/checkout@v2
        
      - name: Install required tools
        run: |
          sudo apt-get install dh-make 
      
      - name: Build package with dpkg-buildpackage
        id: deb
        run: |
          cd sdkjs-plugins/packages/deb/onlyoffice-documentserver-plugin-chess
          dpkg-buildpackage -b -uc -us -d 
          ls -la ../
          pwd ../
          
      - name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          
      - name: Create release 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sdkjs-plugins/packages/deb/onlyoffice-documentserver-plugin-chess_1.0.1_all.deb"

      - name: Release package
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.tag_name.outputs.SOURCE_TAG }}"
          title: "${{ steps.tag_name.outputs.SOURCE_TAG }}"
          prerelease: false
          files: "*.deb"
      
  build_rpm:
    name: Create .rpm package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build RPM package
        id: rpm_build
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "sdkjs-plugins/packages/rpm/onlyoffice-documentserver-plugin-chess.spec"

          
          
          
          
          
