name: Release RPM DEB
on:
  workflow_call:
  workflow_dispatch:
  push: 
    branches: ["feature/Documentserver-plugins-deb-rpm"]
    tags: 
      - '*'

jobs:


  build_deb:
    name: Build & Release .deb package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Get files from repository. Path /home/runner/work/onlyoffice.github.io/onlyoffice.github.io
        uses: actions/checkout@v2
        
      - name: Install required tools
        run: |
          sudo apt-get install dh-make 
      
      - name: Build package with dpkg-buildpackage
        id: deb
        run: |
          cd sdkjs-plugins/packages/deb/onlyoffice-documentserver-plugin-chess
          dpkg-buildpackage -b -uc -us -d 
          ls -la ../
          pwd ../
          
      - name: Create release 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sdkjs-plugins/packages/deb/onlyoffice-documentserver-plugin-chess_1.0.1_all.deb"
          body: Try it!
            - First 
            - Second

      
  build_rpm:
    name: Create .rpm package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build RPM package
        id: rpm_build
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "sdkjs-plugins/packages/rpm/onlyoffice-documentserver-plugin-chess.spec"

          
          
          
          
          
